/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 emodel.gltf --transform
Author: alex.yefremov (https://sketchfab.com/alex.yefremov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ethereum-logo-103abec3ee9045858db28a7657fe2e18
Title: Ethereum logo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Emodel(props) {
  const { nodes, materials } = useGLTF('/emodel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={0.38}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Ethereum_3D_logoObject_0_lambert2_0.geometry} material={materials.lambert2} scale={[1, 0.66, 1]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/emodel-transformed.glb')
